### ISSUE TITLE
Update to @nextcloud/vue 4

### ISSUE THREAD

**Issue by korelstar** [nextcloud/nextcloud-vue-dashboard#233]
Updating apps to `@nextcloud/vue@4` is blocked since  `@nextcloud/vue-dashboard` requires version 3.

**Comment by korelstar** [comment]
By the way: is it still desired to provide these two dashboard components in a separate package? I think maintenance would be much easier after merging this project with `@nextcloud/vue`.

**Comment by juliushaertl** [comment]
I personally prefer small packages for stuff that is not too widely used that is why this started off as a separate one. @skjnldsv Any concrete concerns on moving this over? I have no strong opinion on that.

Anyhow I'll prepare a new release for `@nextcloud/vue@4`

**Comment by mejo-** [comment]
@juliushaertl did you already find time to look into this? Otherwise I could try to allocate some time to it. I'd love to look into a dashboard widget for the Collectives app, but we would need `nextcloud-vue-dashboard` to be ported to `@nextcloud/vue4` first.

**Comment by raimund-schluessler** [comment]
The migration to `nextcloud/vue@5` is not a big deal. The only thing that needs to be adjusted is this line:
https://github.com/nextcloud/nextcloud-vue-dashboard/blob/1e74b6b62588e0003c6a0db83843f2cacc4f0ad4/src/DashboardWidgetItem.vue#L182
that should read
```js
			if (event.target.closest('.action-item')) {
```
now (because there are material design icons used now). I am happy to adjust this, but I would like to get some feedback on #407 first.

**Comment by raimund-schluessler** [comment]
Done with the merge into the vue components in https://github.com/nextcloud/nextcloud-vue/pull/2668
